[build]
  command = "npm run build"
  publish = "dist/app"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 4200
  targetPort = 4200
  publish = "dist/app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200